version: "3.4"
services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - $PWD/config:/etc/influxdb2:rw
      - $PWD/data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  data-generator:
    build: .
    command: python3 write_data_to_influxdb.py
    depends_on:
      - influxdb
    network_mode: "host"
    restart: on-failure
#    privileged: true # will need this for accessing the serial port on raspberry pi

